apiVersion: v1
kind: Service
metadata:
  name: gas-burner
spec:
  selector:
    app: gas-burner
  ports:
    - port: 8080
      targetPort: 8080
      name: health
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-burner
spec:
  stripPrefix:
    prefixes:
      - /burner
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gas-burner
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/burner/healthz`)
      kind: Rule
      middlewares:
        - name: strip-burner
      services:
        - name: gas-burner
          port: 8080
